export const COMMON_ERROR_TOKEN_EXPIRED = "COMMON_ERROR_TOKEN_EXPIRED";
export const COMMON_ERROR_CANNOT_USE_PREVIOUS_PASSWORDS =
  "COMMON_ERROR_CANNOT_USE_PREVIOUS_PASSWORDS";
export const COMMON_ERROR_SYSTEM_VERSION_MISMATCH =
  "COMMON_ERROR_SYSTEM_VERSION_MISMATCH";
export const COMMON_ERROR_USER_VERSION_MISMATCH =
  "COMMON_ERROR_USER_VERSION_MISMATCH";
export const COMMON_ERROR_INVALID_TOKEN = "COMMON_ERROR_INVALID_TOKEN";
